name: lankalink
description: "A new Flutter project."
<<<<<<< Updated upstream
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

=======
publish_to: 'none'
>>>>>>> Stashed changes
version: 1.0.0+1

environment:
  sdk: ^3.5.0 # Use whatever your current SDK version is

dependencies:
  flutter:
    sdk: flutter
<<<<<<< Updated upstream

  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
=======
>>>>>>> Stashed changes
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< Updated upstream
  flutter_lints: ^6.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application.
  uses-material-design: true

  # අකුරු සහ අනෙකුත් ජායාරූප assets ඇතුළත් කිරීම
  assets:
    - assets/fonts/

  # ඔබේ Unicode fonts මෙහි ලියාපදිංචි කිරීම (මෙය අනිවාර්ය වේ)
  fonts:
    - family: UN-Imanee
      fonts:
        - asset: assets/fonts/UN-Imanee.ttf
          weight: 400

    - family: UN-Sandhyanee
      fonts:
        - asset: assets/fonts/UN-Sandhyanee.ttf
          weight: 400
=======
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Custom assets and fonts are declared here
  assets:
    - assets/images/ # Optional: If you have images later

  fonts:
    - family: Poppins # The name you will use in your Dart code
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
>>>>>>> Stashed changes
