// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLX2XJJRUMn1vWl40WKw0MfC3RYE_z9x0',
    appId: '1:500455159127:web:67e951b715e44c5c673a12',
    messagingSenderId: '500455159127',
    projectId: 'lankalink-a85ad',
    authDomain: 'lankalink-a85ad.firebaseapp.com',
    storageBucket: 'lankalink-a85ad.firebasestorage.app',
    measurementId: 'G-Y4VW0SSWRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwait6Tln5Jzhfb4YLnOeWF38ZfNZGwlk',
    appId: '1:500455159127:android:2429df5fb296d0f4673a12',
    messagingSenderId: '500455159127',
    projectId: 'lankalink-a85ad',
    storageBucket: 'lankalink-a85ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhrs9V9rzNryIHNpBPXrcjum3ZgXcHSsQ',
    appId: '1:500455159127:ios:3571de943c02310d673a12',
    messagingSenderId: '500455159127',
    projectId: 'lankalink-a85ad',
    storageBucket: 'lankalink-a85ad.firebasestorage.app',
    iosBundleId: 'com.example.lankalink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhrs9V9rzNryIHNpBPXrcjum3ZgXcHSsQ',
    appId: '1:500455159127:ios:3571de943c02310d673a12',
    messagingSenderId: '500455159127',
    projectId: 'lankalink-a85ad',
    storageBucket: 'lankalink-a85ad.firebasestorage.app',
    iosBundleId: 'com.example.lankalink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLX2XJJRUMn1vWl40WKw0MfC3RYE_z9x0',
    appId: '1:500455159127:windows:d825fe318b86944a673a12',
    messagingSenderId: '500455159127',
    projectId: 'lankalink-a85ad',
    storageBucket: 'lankalink-a85ad.firebasestorage.app',
  );
}
